import type { NextPage } from 'next'
import Head from 'next/head'
import PostSection from '@/components/Post/PostSection'
import { getAllPostsWithFrontMatter } from '@/lib/utils'
import { BlogPostProps } from '@/types'
import Card from '@/components/Card'

type Props = {
  posts: BlogPostProps[]
}

const Home: NextPage<Props> = ({ posts }) => {
  return (
    <div className="flex w-full h-full flex-col py-4 desktop:flex-row">
      <Head>
        <title>@Woongs-World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card />
      <section className="w-full flex justify-center desktop:max-w-[1024px]">
        <PostSection posts={posts} title="All Posts" />
      </section>
    </div>
  )
}

export default Home

export async function getStaticProps(): Promise<{ props: Props }> {
  const posts = await getAllPostsWithFrontMatter()

  return {
    props: {
      posts,
    },
  }
}
